image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          # Dependencies
          - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main" > /etc/apt/sources.list.d/gazebo-stable.list
          - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
          - apt update
          - apt -y install
            cmake pkg-config python cppcheck doxygen ruby-ronn
            mercurial libcurl4-openssl-dev libjsoncpp-dev libzip-dev libgflags-dev
            lcov curl libyaml-dev
            libignition-cmake-dev
            libignition-math4-dev
            libignition-common-dev
          # Ignition tools
          - apt -y install ruby-dev
          - hg clone http://bitbucket.org/ignitionrobotics/ign-tools -b default
          - cd ign-tools
          - mkdir build
          - cd build
          - cmake ..
          - make install
          - cd ../..
          # Style checker first - fail fast
          - sh tools/code_check.sh
          # Ignition Fuel Tools
          - mkdir build && cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make -j4
          - make install
          - make test ARGS="-VV"
          - make coverage
          - bash <(curl -s https://codecov.io/bash)
          - make doc
          # Build examples
          - cd ../example
          - mkdir build && cd build
          - cmake ..
          - make -j4
